import { authFetch as fetch } from './authClient';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Contract, JsonRpcProvider, ZeroHash } from 'ethers';
import { ArrowDownToLine, ArrowRight, Check, FileCheck2, GitCompareArrows, Landmark, LockKeyhole, ShieldCheck, Upload } from 'lucide-react';
import { ClosureRecord, Comparison, ProofPacket, anchorFingerprint, challengeText, compareClosure, trustAnchor, verifyClosure, verifyPacket } from '../../../shared/closure';
import { ReceiptFile, caseLabel, verifyReceipt } from '../../../shared/receipt';
import { checkClosureOnChain, signClosureRecord } from './closureChain';
import { Badge, Button, CopyValue, ErrorBox, Progress, date } from './ui';

function saveFile(name: string, value: string, type='application/json') {
  const url=URL.createObjectURL(new Blob([value],{type})); const link=document.createElement('a'); link.href=url; link.download=name; link.click(); setTimeout(()=>URL.revokeObjectURL(url),1000);
}
const readFile = async (file: File, limit: number) => {
  if (!file.name.toLowerCase().endsWith('.json') || (file.type && !['application/json','application/octet-stream'].includes(file.type))) throw new Error('Choose a JSON signed record, receipt or proof packet. Original PDF/image evidence stays in Your receipts.');
  if (!file.size || file.size>limit) throw new Error(`File size must be between 1 byte and ${limit/1024} KB.`);
  try { return JSON.parse(await file.text()); } catch { throw new Error('The selected file is not valid JSON.'); }
};
type Props = { config: any; rpc: JsonRpcProvider; selected: string; department: boolean; receipt: ReceiptFile | null; onSurface: (receipt: ReceiptFile) => void; onDepartment: () => void; onTransaction: (hash: string) => void };
export default function EvidenceCheck({config,rpc,selected,department,receipt,onSurface,onDepartment,onTransaction}: Props) {
  const anchor=useMemo(()=>trustAnchor(config),[config]), storage=`decisiontrail:closures:${config.userId || "local"}:${config.deploymentBlockHash}:${selected}`;
  const [records,setRecords]=useState<ClosureRecord[]>([]), [record,setRecord]=useState<ClosureRecord|null>(null), [receipts,setReceipts]=useState<ReceiptFile[]>([]);
  const [error,setError]=useState(''), [progress,setProgress]=useState(''), [live,setLive]=useState<'UNCHECKED'|'CHECKING'|'MATCHED'|'UNAVAILABLE'|'CONFLICT'>('UNCHECKED'), [liveError,setLiveError]=useState('');
  const [current,setCurrent]=useState<Record<string,string>>({});
  const recordInput=useRef<HTMLInputElement>(null), receiptInput=useRef<HTMLInputElement>(null), packetInput=useRef<HTMLInputElement>(null);
  const busy=!!progress;
  useEffect(()=>{
    setError('');setRecord(null);setReceipts([]);setCurrent({});setLive('UNCHECKED');setLiveError('');
    try { const saved=JSON.parse(localStorage.getItem(storage)||'[]'); const valid:ClosureRecord[]=saved.filter((r:ClosureRecord)=>{try{verifyClosure(r,anchor);return r.statement.caseId===selected;}catch{return false;}});setRecords(valid);setRecord(valid.at(-1)||null); }
    catch {setRecords([]);}
  },[storage,anchor,selected]);
  let comparison:Comparison|null=null, comparisonError='';
  if(record&&receipts.length){try{comparison=compareClosure(record,receipts,anchor);}catch(e:any){comparisonError=e.message;}}
  const comparisonKey=record?.signature+':'+receipts.map(r=>r.signature).join(':');
  useEffect(()=>{
    let active=true;setCurrent({});
    if(!record){setLive('UNCHECKED');return;}
    setLive('CHECKING');setLiveError('');
    (async()=>{
      await checkClosureOnChain(record,config,rpc);
      const registry=new Contract(config.contracts.KeyRegistry.address,config.contracts.KeyRegistry.abi,rpc);
      const manager=new Contract(config.contracts.DisputeManager.address,config.contracts.DisputeManager.abi,rpc);
      const statuses:Record<string,string>={};
      for(const file of receipts){const checked=verifyReceipt(file,anchor);if(!await registry.isKeyValidAt(file.receipt.institutionId,checked.signer,file.receipt.timestamp))throw new Error('An applicant receipt key was not valid at the stated acknowledgement time.');const registered=await manager.registeredReceipts(checked.digest);const response=registered?await manager.dispositions(checked.digest):ZeroHash;statuses[checked.digest]=!registered?'Not registered':response===ZeroHash?'Registered · unresolved':'Disposition recorded';}
      if(active){setLive('MATCHED');setCurrent(statuses);}
    })().catch(e=>{if(active){setLive(e.code==='PROOF_MISMATCH'?'CONFLICT':'UNAVAILABLE');setLiveError(e.shortMessage||e.message);}});
    return()=>{active=false;};
  },[comparisonKey,config,rpc]);
  function remember(next:ClosureRecord){verifyClosure(next,anchor);if(next.statement.caseId!==selected)throw new Error('This closure record belongs to another application. Select that case first.');const nextRecords=records.some(r=>r.signature===next.signature)?records:[...records,next];localStorage.setItem(storage,JSON.stringify(nextRecords));setRecords(nextRecords);setRecord(next);}
  async function retrieve(){setError('');setProgress('Reading department-signed closure records�');try{const response=await fetch((import.meta.env.VITE_API_URL || '') + '/api/closures/'+selected);const saved=await response.json();if(!response.ok)throw new Error(saved.error);if(!saved.length)throw new Error('The department has not published a signed closure record yet. Ask them to create one after sealing.');for(const value of saved)verifyClosure(value,anchor);localStorage.setItem(storage,JSON.stringify(saved));setRecords(saved);setRecord(saved.at(-1));}catch(e:any){setError(e.message);}finally{setProgress('');}}
  async function publish(){setError('');try{const signed=await signClosureRecord(config,rpc,selected,setProgress);remember(signed);}catch(e:any){setError(e.shortMessage||e.message);}finally{setProgress('');}}
  async function importRecord(file?:File){if(!file)return;setError('');setRecord(null);setReceipts([]);setProgress('Checking closure signature and inventory...');try{const next=await readFile(file,1024*1024);verifyClosure(next,anchor);remember(next);setReceipts([]);}catch(e:any){setError(e.message);}finally{setProgress('');}}
  function addReceipts(incoming:ReceiptFile[]){if(!record)throw new Error('Import a signed closure record first.');const next=[...receipts];for(const file of incoming){const checked=verifyReceipt(file,anchor);if(!next.some(r=>verifyReceipt(r,anchor).digest===checked.digest))next.push(file);}compareClosure(record,next,anchor);setReceipts(next);}
  async function importReceipts(files:FileList|null){if(!files)return;setError('');setProgress('Verifying applicant-held receipts...');try{if(files.length>32)throw new Error('Choose up to 32 signed receipts at a time.');const added=[];for(const file of Array.from(files)){added.push(await readFile(file,128*1024));}addReceipts(added);}catch(e:any){setError(e.message);}finally{setProgress('');}}
  async function useReceipt(){setError('');setProgress('Reading the applicant-held receipt...');try{if(receipt&&receipt.receipt.caseId===selected)addReceipts([receipt]);else{const response=await fetch((import.meta.env.VITE_API_URL || '') + `/api/receipt/${selected}`);if(!response.ok)throw new Error('Receipt could not be retrieved. Import your retained copy.');addReceipts([await response.json()]);}}catch(e:any){setError(e.message);}finally{setProgress('');}}
  async function importPacket(file?:File){if(!file)return;setError('');setRecord(null);setReceipts([]);setProgress('Checking packet signatures and comparison...');try{const packet=await readFile(file,1024*1024);verifyPacket(packet,anchor);remember(packet.record);setReceipts(packet.receipts);}catch(e:any){setError(e.message);}finally{setProgress('');}}
  const packet:ProofPacket|null=record&&comparison?{schema:'decisiontrail/proof-packet-v1',record,receipts}:null;
  async function downloadVerifier(){setError('');try{const response=await fetch((import.meta.env.VITE_API_URL || '') + '/offline-verifier.html');if(!response.ok)throw new Error('Offline verifier not built. Run npm run build:verifier, then retry.');let html=await response.text();if(!html.includes('{"pin":null}'))throw new Error('Offline verifier template is invalid.');html=html.replace('{"pin":null}',JSON.stringify({pin:anchor}).replace(/</g,'\\u003c'));saveFile('DecisionTrail-offline-verifier.html',html,'text/html');}catch(e:any){setError(e.message);}}
  return <div className="evidence-check">
    <section className="evidence-intro"><div><span className="section-kicker">A RECEIPT YOU CAN STAND BEHIND</span><h2>Closed. But was your receipt included?</h2><p>Compare what you hold with a signed record of what the registry contained when it closed. Keep the result, even when the portal is unavailable.</p></div><span className="evidence-symbol"><GitCompareArrows size={38}/></span></section>
    <div className="evidence-boundary"><ShieldCheck size={18}/><p><strong>A precise claim.</strong> This checks registered receipts at a specific seal. It does not prove an officer ignored evidence in another system, or that a decision was wrong.</p></div>
    <input type="file" className="visually-hidden" ref={recordInput} accept=".json,application/json" aria-label="Import signed closure record" onChange={e=>{void importRecord(e.target.files?.[0]);e.target.value='';}}/>
    <input type="file" className="visually-hidden" ref={receiptInput} accept=".json,application/json" multiple aria-label="Import applicant receipts for comparison" onChange={e=>{void importReceipts(e.target.files);e.target.value='';}}/>
    <input type="file" className="visually-hidden" ref={packetInput} accept=".json,application/json" aria-label="Import portable proof packet" onChange={e=>{void importPacket(e.target.files?.[0]);e.target.value='';}}/>
    <div className="evidence-columns"><section className="evidence-panel"><div className="panel-label"><Landmark size={18}/> 01 / THE SIGNED CLOSURE RECORD</div><h3>What the registry contained.</h3><p>The department signs the complete list of registered receipt digests at a confirmed seal. The statement is signed now about that earlier block.</p>
      {department?<Button onClick={publish} disabled={busy}>Create signed closure record <ShieldCheck size={16}/></Button>:<Button kind="secondary" onClick={()=>recordInput.current?.click()} disabled={busy}><Upload size={16}/> Import closure record</Button>}
      {!department&&config.productMode&&<Button kind="secondary" onClick={retrieve} disabled={busy}>Get department closure record</Button>}{department&&<button className="text-link" disabled={busy} onClick={()=>recordInput.current?.click()}>Import an existing record</button>}
      {!config.productMode&&!record&&!department&&<button className="text-link" onClick={onDepartment}>Demo: get the department’s signed record <ArrowRight size={14}/></button>}
      {record&&<div className="closure-summary"><Badge tone="success">ISSUER SIGNATURE CHECKED</Badge><dl><div><dt>Application</dt><dd>{caseLabel(record.statement.caseId)}</dd></div><div><dt>Registered receipts at seal</dt><dd>{record.inventory.length}</dd></div><div><dt>Snapshot block</dt><dd>{record.statement.blockNumber}</dd></div><div><dt>Snapshot time</dt><dd>{date(Number(record.statement.blockTimestamp))}</dd></div></dl><button className="text-link" onClick={()=>onTransaction(record.statement.sealTransaction)}>View actual seal transaction <ArrowRight size={14}/></button><Button kind="secondary" onClick={()=>saveFile(`DecisionTrail-${caseLabel(selected)}-closure.json`,JSON.stringify(record,null,2))}><ArrowDownToLine size={15}/> Download closure record</Button>{records.length>1&&<label>Retained signed snapshots<select aria-label="Retained signed snapshots" value={record.signature} onChange={e=>setRecord(records.find(r=>r.signature===e.target.value)||null)}>{records.map((r,i)=><option key={r.signature} value={r.signature}>#{i+1} · block {r.statement.blockNumber} · {r.inventory.length} receipts</option>)}</select></label>}</div>}
    </section><section className="evidence-panel"><div className="panel-label"><FileCheck2 size={18}/> 02 / YOUR RETAINED RECEIPTS</div><h3>What was acknowledged.</h3><p>Supply your signed receipts. Each signature and application binding is checked before comparing the exact receipt digest.</p><Button kind="secondary" disabled={!record||busy} onClick={()=>receiptInput.current?.click()}><Upload size={16}/> Add applicant receipts</Button><button className="text-link" disabled={!record||busy} onClick={useReceipt}>{receipt&&receipt.receipt.caseId===selected?'Use your imported receipt':`Use issued receipt ${caseLabel(selected)}`} <ArrowRight size={14}/></button><div className="retained-count"><strong>{receipts.length}</strong><span>applicant-held receipts<br/>selected for comparison</span></div>{receipts.length>0&&<button className="text-link" onClick={()=>setReceipts([])}>Clear selected receipts</button>}<p className="privacy-note"><LockKeyhole size={14}/> No original document bytes are needed in this comparison.</p></section></div>
    {progress&&<Progress text={progress}/>}{(error||comparisonError)&&<ErrorBox message={error||comparisonError}/>}
    {record&&<div className={`closure-live ${live==='MATCHED'?'matched':''}`} role="status"><ShieldCheck size={17}/><div><strong>{live==='MATCHED'?'Signed snapshot matches the live chain':live==='CHECKING'?'Checking the signed snapshot against the chain':live==='CONFLICT'?'Signed snapshot conflicts with the live chain':'Live chain check unavailable'}</strong><p>{live==='MATCHED'?'Block hash, seal transaction and the complete registered-receipt inventory were independently re-read.':liveError||'Signature comparison remains separate from current blockchain verification.'}</p></div></div>}
    {comparison&&record&&<section className={`reconciliation-result ${comparison.missing?'has-gap':'no-gap'}`} data-testid="reconciliation-result" aria-live="polite"><div className="reconciliation-heading"><div><span className="section-kicker">03 / THE RECONCILIATION</span><h2>{comparison.missing?`${comparison.missing} acknowledged receipt${comparison.missing===1?' is':'s are'} missing.`:'No gap among the supplied receipts.'}</h2><p>{comparison.missing?`Missing from the signed registry inventory at block ${record.statement.blockNumber}. This historical comparison stays intact after later registration.`:'Only the receipts you supplied are covered. This is not a completeness claim for all evidence.'}</p></div><Badge tone={comparison.missing?'warning':'success'}>{comparison.missing?'GAP IN SIGNED RECORD':'COMPARISON COMPLETE'}</Badge></div>
      <div className="comparison-table" role="table" aria-label="Receipt reconciliation"><div className="comparison-table-head" role="row"><span role="columnheader">Applicant receipt</span><span role="columnheader">At this closure</span><span role="columnheader">Current registry</span></div>{comparison.rows.map(row=><div role="row" className="comparison-row" key={row.digest}><div role="cell"><strong>{row.label} · {row.evidenceCount} evidence item{row.evidenceCount===1?'':'s'}</strong><CopyValue value={row.digest}/></div><div role="cell"><Badge tone={row.status==='MISSING'?'warning':row.status==='LATER'?'neutral':'success'}>{row.status==='MISSING'?'NOT LISTED':row.status==='LATER'?'DATED AFTER CLOSURE':'LISTED'}</Badge><small>{row.status==='LATER'?'No omission claim for this receipt.':row.status==='LISTED'?'Registered digest appears in the signed list.':'Receipt is dated before this closure snapshot.'}</small></div><div role="cell"><strong>{current[row.digest]||'Not checked'}</strong>{!department&&row.status==='MISSING'&&current[row.digest]==='Not registered'&&<button className="text-link" onClick={()=>onSurface(row.receipt)}>Bring to registration <ArrowRight size={14}/></button>}</div></div>)}</div>
      <div className="portable-proof"><div><h3>Keep the proof outside the portal.</h3><p>Export both signatures and the complete signed inventory. The offline verifier redoes the comparison; it does not trust a saved result label.</p></div><div className="proof-actions"><Button onClick={()=>packet&&saveFile(`DecisionTrail-${caseLabel(selected)}-proof.json`,JSON.stringify(packet,null,2))}><ArrowDownToLine size={16}/> Download proof packet</Button><Button kind="secondary" onClick={downloadVerifier}>Download offline verifier</Button><button className="text-link" onClick={()=>packet&&saveFile(`DecisionTrail-${caseLabel(selected)}-reconciliation.txt`,challengeText(packet,anchor),'text/plain')}>Download factual report <ArrowDownToLine size={14}/></button></div></div>
      <p className="comparison-limits">The packet contains commitments and signatures, not your documents. Offline checks do not establish current chain state or canonical block inclusion. Receipt dates are issuer-signed claims. No grievance is automatically submitted.</p>
    </section>}
    <div className="packet-import"><div><strong>Already have a proof packet?</strong><p>Import and recompute its signatures and comparison against this deployment.</p></div><Button kind="secondary" onClick={()=>packetInput.current?.click()} disabled={busy}>Import proof packet <Upload size={16}/></Button></div>
    <details className="evidence-trust"><summary>Trust anchor and what this proves</summary><p>The expected issuer is configured independently of an imported packet. Your exported verifier pins this deployment. Confirm its fingerprint through a trusted source before relying on a shared verifier.</p><div><span>EXPECTED ISSUER</span><CopyValue value={anchor.issuer} full/></div><div><span>TRUST FINGERPRINT</span><CopyValue value={anchorFingerprint(anchor)} full/></div><p>Live: receipt/closure signatures, historical issuer validity, the canonical block reported by the connected node, seal transaction and full registry inventory. Offline: signatures under the pinned issuer, inventory integrity, case binding and receipt-list comparison. Neither mode proves factual truth, legal error or completeness of off-chain departmental files.</p></details>
  </div>;
}
