import React, { useEffect, useState } from 'react';
import { ArrowRight, ArrowDown, ArrowUpRight, FileCheck2, Fingerprint, LockKeyhole, Check, X, ShieldCheck, Landmark, ScanLine, RotateCcw, FileText, GitBranch, Scale, ChevronRight } from 'lucide-react';
import { Badge, Brand, Button, ReceiptCard, ErrorBox } from './ui';
import { verifyReceipt, caseLabel } from '../../../shared/receipt';
import { encodeBytes32String } from 'ethers';

export function TamperLab({ config, file, load }: { config: any; file: any; load: () => void }) {
  const [label, setLabel] = useState('');
  const original = file ? caseLabel(file.receipt.caseId) : 'R17';
  const current = label || original;
  let valid = false, error = '';
  if (file && config) { try { verifyReceipt({ ...file, receipt: { ...file.receipt, caseId: encodeBytes32String(current) } }, config); valid = true; } catch (e: any) { error = e.message; } }
  return <div className="tamper-lab"><div className="tamper-left"><div className="section-kicker"><Fingerprint size={15}/> CRYPTOGRAPHY, YOU CAN CHECK</div><h2>One changed field.<br/>A broken signature.</h2><p>A receipt is only as trustworthy as its verification. Change the case reference and check what the original signature actually proves.</p><div className="lab-note"><ShieldCheck size={16}/><span>Real EIP-712 signature recovery, in your browser.</span></div></div><div className="tamper-console"><div className="console-head"><span><span className="status-dot"/> RECEIPT VERIFIER</span><Badge tone="neutral">SYNTHETIC DATA</Badge></div><div className="tamper-field"><label htmlFor="tamper-case">SIGNED CASE REFERENCE</label><div><input id="tamper-case" value={current} maxLength={30} disabled={!file} onChange={e => setLabel(e.target.value)} aria-describedby="tamper-result"/><span>EDIT THIS FIELD ↗</span></div></div><div className="console-row"><span>Evidence commitments</span><span>{file ? file.receipt.docCommitments.length : '—'}</span></div><div className="console-row"><span>Signature format</span><span>EIP-712</span></div><div id="tamper-result" aria-live="polite" className={`signature-result ${!file ? '' : valid ? 'valid' : 'invalid'}`}>{!file ? <><ScanLine size={21}/><div><strong>Ready to verify</strong><p>Load a signed fixture from your local deployment.</p></div></> : valid ? <><ShieldCheck size={24}/><div><strong>Signature valid</strong><p>The signed data matches the trusted issuer.</p></div></> : <><X size={24}/><div><strong>Signature invalid</strong><p>{error.includes('signed fields') ? 'The signed data no longer matches the receipt.' : error}</p></div></>}</div><div className="lab-actions">{!file ? <Button kind="secondary" onClick={load} disabled={!config}>Load signed receipt <ArrowDown size={16}/></Button> : <><Button kind="secondary" onClick={() => setLabel(current === original ? 'R99' : original)}>{current === original ? 'Modify receipt' : 'Restore original'} {current === original ? <ArrowUpRight size={16}/> : <RotateCcw size={16}/>}</Button><span>{valid ? 'Original signature retained' : 'No blockchain state changed'}</span></>}</div></div></div>;
}
const phases = [
  { label: 'Evidence enters the workflow', status: 'DOCUMENT SUBMITTED', detail: 'Three evidence items reach the department.', tone: 'neutral', index: 0 },
  { label: 'Evidence acknowledged', status: 'ACKNOWLEDGED', detail: 'The institution signs what it received.', tone: 'success', index: 0 },
  { label: 'You keep the proof', status: 'RETAINED', detail: 'The receipt stays with the applicant.', tone: 'success', index: 1 },
  { label: 'The audit is closed', status: 'SEALED', detail: 'But acknowledged evidence is missing.', tone: 'neutral', index: 2 },
  { label: 'The receipt is presented', status: 'REGISTERED', detail: 'The applicant registers the signed receipt.', tone: 'success', index: 3 },
  { label: 'The record reopens', status: 'REOPENED', detail: 'An outstanding obligation is created.', tone: 'warning', index: 4 },
  { label: 'The department tries to close', status: 'CLOSURE ATTEMPT', detail: 'The registry checks outstanding obligations.', tone: 'warning', index: 5 },
  { label: 'Premature closure blocked', status: 'BLOCKED', detail: 'The contract requires evidence to be accounted for.', tone: 'error', index: 5 },
  { label: 'The evidence is accounted for', status: 'DISPOSITION RECORDED', detail: 'The outstanding obligation is resolved.', tone: 'success', index: 6 },
  { label: 'The updated record is committed', status: 'CHECKPOINT APPENDED', detail: 'A new checkpoint preserves continuity.', tone: 'success', index: 6 },
  { label: 'The record closes again', status: 'SEALED AGAIN', detail: 'Nothing that happened before disappears.', tone: 'success', index: 6 },
];
export default function Landing({ launch, config, sample, loadSample, error }: { launch: () => void; config: any; sample: any; loadSample: () => void; error: string }) {
  const [phase, setPhase] = useState(0), [playing, setPlaying] = useState(true);
  useEffect(() => { if (!playing || matchMedia('(prefers-reduced-motion: reduce)').matches) return; const timer = setInterval(() => setPhase(v => (v + 1) % phases.length), 3100); return () => clearInterval(timer); }, [playing]);
  const p = phases[phase];
  return <div className="landing"><header className="site-header"><div className="nav-inner"><Brand onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}/><nav aria-label="Main navigation"><a href="#how-it-works">How it works</a><a href="#why-it-matters">Why it matters</a><a href="#trust">Trust model</a><a href="#technology">Technology</a></nav><Button kind="small" onClick={launch}>Launch demo <ArrowUpRight size={16}/></Button></div></header>
    <main><section className="hero page-width"><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> A RECORD THAT ANSWERS TO YOU</div><h1>When your<br/>evidence matters,<br/><span>keep the receipt.</span></h1><p>DecisionTrail gives you a signed, independently verifiable receipt for acknowledged evidence — and a way to surface it when it disappears from the audit record.</p><div className="hero-ctas"><Button onClick={launch}>Experience the demo <ArrowUpRight size={18}/></Button><a className="quiet-link" href="#how-it-works">See how it works <ArrowDown size={16}/></a></div><div className="hero-footnote"><span>YOUR EVIDENCE.</span><span>YOUR RECEIPT.</span><span>YOUR TRAIL.</span></div></div>
      <div className="hero-scene"><div className="scene-grid"/><div className="scene-label"><span className="status-dot"/> THE ACCOUNTABILITY LOOP <span>ILLUSTRATED FLOW</span></div><div className={`hero-receipt phase-${p.index}`}><ReceiptCard illustrative/></div><div className={`scene-state ${p.tone}`} key={phase}><span className="scene-icon">{p.tone === 'error' ? <X size={23}/> : p.tone === 'warning' ? <GitBranch size={23}/> : <ShieldCheck size={23}/>}</span><div><small>{p.status}</small><strong>{p.label}</strong><p>{p.detail}</p></div></div><div className="scene-bottom"><div className="phase-buttons">{phases.map((s, i) => <button key={s.status} className={i === phase ? 'active' : ''} onClick={() => { setPhase(i); setPlaying(false); }} aria-label={`Show ${s.status}`} aria-pressed={i === phase}/>)}</div><button className="animation-toggle" onClick={() => setPlaying(!playing)}>{playing ? 'Pause' : 'Play'} sequence</button></div><div className="scene-caption">The institution keeps the workflow.<br/><strong>You keep the proof.</strong></div></div>
    </section>
    <div className="principle-strip page-width"><div><span>01</span><FileCheck2 size={20}/><p>Signed acknowledgement</p></div><div><span>02</span><Fingerprint size={20}/><p>Independent verification</p></div><div><span>03</span><GitBranch size={20}/><p>Shared accountability</p></div><span className="strip-note">A LOCAL, WORKING PROTOTYPE <ArrowDown size={14}/></span></div>
    <section id="why-it-matters" className="section page-width"><div className="section-kicker">01 / THE MISSING LINK</div><div className="section-heading"><h2>A status is not<br/>the whole story.</h2><p>A status page tells you what happened.<br/>It doesn't always tell you what was accounted for.</p></div><div className="comparison"><article className="comparison-card muted"><div className="comparison-title"><span className="outline-icon"><FileText size={21}/></span><h3>Without a retained receipt</h3></div><div className="flow-chips">{['Submitted', 'Acknowledged', 'Processing', 'Rejected'].map((x, i) => <React.Fragment key={x}><span>{x}</span>{i < 3 && <ChevronRight size={13}/>}</React.Fragment>)}</div><div className="comparison-outcome"><span className="missing-mark">?</span><div><strong>“Where did my document go?”</strong><p>The workflow ends. The question remains.</p></div></div></article><article className="comparison-card with-proof"><div className="comparison-title"><span className="outline-icon"><ShieldCheck size={21}/></span><h3>With DecisionTrail</h3><span className="tiny-label">PROOF YOU HOLD</span></div><div className="flow-chips">{['Submitted', 'Signed receipt', 'Retained', 'Verified'].map((x, i) => <React.Fragment key={x}><span>{x}</span>{i < 3 && <ChevronRight size={13}/>}</React.Fragment>)}</div><div className="comparison-outcome"><ShieldCheck size={28}/><div><strong>A receipt that can reopen the record.</strong><p>Acknowledged evidence gets accounted for.</p></div></div></article></div></section>
    <section id="how-it-works" className="section process-section"><div className="page-width"><div className="section-kicker">02 / FROM EVIDENCE TO ACCOUNTABILITY</div><div className="section-heading"><h2>One receipt.<br/>An unbroken trail.</h2><p>The bridge between what was acknowledged<br/>and what was recorded.</p></div><div className="steps-grid">{[
      ['01', 'Submit', 'Your evidence is acknowledged.', 'Your submission enters the institution’s normal workflow.', FileText],
      ['02', 'Receive', 'A signed receipt is created.', 'The signature binds the issuer to what it acknowledged.', FileCheck2],
      ['03', 'Retain', 'You keep the receipt.', 'Your copy exists outside the institution’s workflow.', LockKeyhole],
      ['04', 'Verify', 'Check the signature.', 'Independently recover and verify the trusted issuer.', Fingerprint],
      ['05', 'Surface', 'Present it independently.', 'Register a valid receipt directly with the shared contract.', ArrowUpRight],
      ['06', 'Account', 'Prevent premature closure.', 'Resolve the obligation before the record can close.', ShieldCheck],
    ].map(([num, title, subtitle, detail, Icon]: any) => <article className="step-card" key={num}><div><span>{num}</span><Icon size={24}/></div><span className="step-name">{title}</span><h3>{subtitle}</h3><p>{detail}</p></article>)}</div></div></section>
    <section id="technology" className="section page-width technology"><div><div className="section-kicker">03 / PURPOSE-BUILT INFRASTRUCTURE</div><h2>Blockchain has<br/>one job here.</h2><p className="section-lead">Enforce the shared accountability state.</p><p className="body-muted">Private evidence stays off-chain. The contract enforces only the state that must be shared.</p><div className="technology-tags"><span>Solidity</span><span>EIP-712</span><span>Local Hardhat</span></div></div><div className="architecture"><div className="architecture-actors"><span><Landmark size={23}/>DEPARTMENT</span><span><FileCheck2 size={23}/>APPLICANT</span></div><div className="architecture-lines"><i/><i/></div><div className="registry-node"><span className="brand-symbol"><i/><i/><i/></span><div><small>THE SHARED SOURCE OF TRUTH</small><strong>Accountability registry</strong></div><ShieldCheck size={22}/></div><div className="registry-rules"><div><b>Register</b><span>Create an obligation</span></div><div><b>Reopen</b><span>Surface an omission</span></div><div><b>Enforce</b><span>Reject premature closure</span></div></div></div></section>
    <section className="section page-width" id="tamper"><TamperLab config={config} file={sample} load={loadSample}/>{error && <ErrorBox message={error} onRetry={loadSample}/>}</section>
    <section id="trust" className="section page-width"><div className="section-kicker">04 / TRUST, WITH CLEAR BOUNDARIES</div><div className="section-heading"><h2>Precisely what it proves.<br/>Honestly what it doesn't.</h2><p>Trust comes from explicit boundaries.<br/>These are ours.</p></div><div className="trust-grid">{[['Receipt authenticity', 'The trusted issuer’s signature can be independently verified.', Fingerprint], ['Audit-state enforcement', 'Registered obligations prevent contract closure.', LockKeyhole], ['Historical continuity', 'Reopening adds to the record. Earlier events remain.', GitBranch], ['Tamper detection', 'Changing signed fields causes verification to fail.', ShieldCheck]].map(([title, text, Icon]: any) => <article key={title}><Icon size={22}/><h3>{title}</h3><p>{text}</p><Check size={17} className="trust-check"/></article>)}</div><div className="boundaries"><div><Scale size={24}/><h3>An accountability record.<br/>A clearly defined scope.</h3></div><ul><li>Does not prove that the evidence itself is true.</li><li>Does not establish that a decision is legally wrong.</li><li>Reopening does not automatically reverse a decision.</li><li>Cannot discover an unacknowledged submission.</li><li>Does not replace government systems.</li><li>A transaction is not a court order.</li></ul></div></section>
    <section className="final-cta page-width"><div className="eyebrow">HISTORY ACCUMULATES. IT DOESN'T DISAPPEAR.</div><h2>Accountability shouldn't disappear<br/>when the workflow does.</h2><p>Give acknowledged evidence a durable place in the audit record.</p><Button onClick={launch}>Launch the 3-minute demo <ArrowUpRight size={18}/></Button><a href="#trust" className="quiet-link">Explore the trust model <ArrowRight size={15}/></a></section>
    <section id="roadmap" className="roadmap page-width"><Badge>ROADMAP</Badge><p>Government integrations · DigiLocker · Production identity and storage · Independent witness network · Full policy replay</p><span>Not part of this prototype</span></section></main>
    <footer className="page-width site-footer"><div><Brand onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}/><p>Your evidence. Your receipt. Your trail.</p></div><div className="footer-links"><a href="#technology">Technology</a><a href="#trust">Trust model</a><button onClick={launch}>Demo</button><a href="#roadmap">Roadmap</a></div><div className="footer-bottom"><span>Prototype · Local deployment · Synthetic data</span><p>Demonstrates receipt accountability. Does not establish legal validity or automatically reverse institutional decisions.</p></div></footer>
  </div>;
}
