const { chromium, expect } = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const output = process.env.DT_TEST_OUTPUT || path.resolve(__dirname, '../.qa-results');
fs.mkdirSync(output, { recursive: true });
const base = process.env.DT_TEST_URL || 'http://127.0.0.1:5174';
(async () => {
  const browser = await chromium.launch({ channel: process.env.DT_BROWSER_CHANNEL === 'chromium' ? undefined : (process.env.DT_BROWSER_CHANNEL || 'msedge'), headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  try {
    await page.goto(base);
    await expect(page.getByRole('heading', { name: /When your/ })).toBeVisible();
    await page.screenshot({ path: path.join(output, 'landing-desktop.png'), fullPage: false });
    await page.getByRole('button', { name: 'Experience the demo' }).click();
    await expect(page.getByRole('heading', { name: /Choose your perspective/ })).toBeVisible();
    await page.screenshot({ path: path.join(output, 'roles.png') });
    await page.getByRole('button', { name: /Enter applicant view/ }).click();
    await expect(page.getByRole('heading', { name: 'Bring your receipt.' })).toBeVisible({ timeout: 30000 });
    await page.screenshot({ path: path.join(output, 'applicant-import.png') });
    const config = await (await page.request.get(`${base}/api/config`)).json();
    const original = await (await page.request.get(`${base}/api/receipt/${config.cases[0].caseId}`)).json();
    const bad = structuredClone(original); bad.receipt.docCommitments[0] = '0x' + 'f'.repeat(64);
    await page.getByLabel('Choose receipt or evidence file').setInputFiles({ name: 'tampered.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(bad)) });
    await expect(page.getByRole('alert')).toContainText('Receipt verification failed');
    await expect(page.getByRole('button', { name: 'Register this receipt' })).toHaveCount(0);
    // Native file input and drag/drop both exercise the same bounded JSON importer.
    const wrongDomain = structuredClone(original); wrongDomain.domain.chainId = 1;
    await page.getByLabel('Choose receipt or evidence file').setInputFiles({ name: 'wrong-deployment.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(wrongDomain)) });
    await expect(page.getByRole('alert')).toContainText('another deployment');
    await page.getByLabel('Choose receipt or evidence file').setInputFiles({ name: 'malformed.json', mimeType: 'application/json', buffer: Buffer.from('{invalid') });
    await expect(page.getByRole('alert')).toContainText('Invalid receipt JSON');
    const drop = await page.evaluateHandle(content => { const transfer = new DataTransfer(); transfer.items.add(new File([content], 'R17.json', { type: 'application/json' })); return transfer; }, JSON.stringify(original));
    await page.locator('.drop-zone').dispatchEvent('drop', { dataTransfer: drop });
    await expect(page.getByRole('heading', { name: 'Receipt verified' })).toBeVisible();
    await page.reload();
    await expect(page.getByRole('heading', { name: 'Receipt verified' })).toBeVisible();
    await page.screenshot({ path: path.join(output, 'receipt-verified.png') });
    await page.getByRole('button', { name: 'Register this receipt' }).click();
    const tx = page.getByRole('dialog', { name: 'Register your receipt' });
    await expect(tx.getByRole('heading', { name: 'Audit reopened' })).toBeVisible({ timeout: 30000 });
    await tx.getByRole('button', { name: 'Continue to the record' }).click();
    await page.getByRole('button', { name: 'Switch to department' }).click();
    await expect(page.getByRole('heading', { name: 'The record is open again.' })).toBeVisible();
    await page.getByRole('button', { name: 'Attempt closure', exact: true }).click();
    await page.getByRole('dialog', { name: 'Seal audit' }).getByRole('button', { name: 'Attempt closure' }).click();
    await expect(page.getByRole('heading', { name: 'Closure blocked' })).toBeVisible({ timeout: 30000 });
    await expect(page.getByRole('dialog', { name: 'Seal audit' })).toContainText('UNCHANGED');
    await page.screenshot({ path: path.join(output, 'closure-blocked.png') });
    await page.getByRole('dialog', { name: 'Seal audit' }).getByRole('button', { name: 'View transaction', exact: true }).click();
    const drawer = page.getByRole('dialog', { name: 'Transaction details' });
    await expect(drawer).toContainText('REVERTED');
    await expect(drawer.getByText('Gas used', { exact: true })).toBeVisible();
    await drawer.getByRole('button', { name: 'Close dialog' }).click();
    await page.getByRole('button', { name: 'Return to audit' }).click();
    await page.getByRole('button', { name: 'Account for R17', exact: true }).click();
    await page.getByRole('dialog', { name: 'Account for receipt R17' }).getByRole('button', { name: 'Record disposition' }).click();
    await expect(page.getByRole('heading', { name: 'Disposition recorded', exact: true })).toBeVisible({ timeout: 30000 });
    await page.getByRole('button', { name: 'Return to audit' }).click();
    await page.getByRole('button', { name: 'Append checkpoint', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Checkpoint appended', exact: true })).toBeVisible({ timeout: 30000 });
    await page.getByRole('button', { name: 'Return to audit' }).click();
    await page.getByRole('button', { name: 'Seal audit', exact: true }).click();
    await page.getByRole('dialog', { name: 'Seal audit' }).getByRole('button', { name: 'Seal audit', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Audit sealed', exact: true })).toBeVisible({ timeout: 30000 });
    await page.getByRole('button', { name: 'Return to audit' }).click();
    await page.getByRole('button', { name: 'Audit history', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Audit sealed', exact: true })).toHaveCount(2);
    await expect(page.getByRole('heading', { name: 'Closure attempt rejected' })).toBeVisible();
    await page.screenshot({ path: path.join(output, 'audit-history.png'), fullPage: true });
    await page.reload();
    await page.getByRole('button', { name: 'Audit history', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Closure attempt rejected' })).toBeVisible();
    const state = await (await page.request.get(`${base}/api/state/${config.cases[0].caseId}`)).json();
    if (state.state !== 'SEALED' || state.outstanding !== 0) throw new Error('Final contract state did not match the UI.');
    const failed = state.history.find(e => e.name === 'ClosureRejected');
    if (!failed || failed.status !== 'REVERTED' || !failed.hash || !failed.blockNumber) throw new Error('Missing actual reverted transaction.');
    fs.writeFileSync(path.join(output, 'e2e-chain-evidence.json'), JSON.stringify(state, null, 2));
    await page.getByRole('button', { name: 'Receipt verifier', exact: true }).click();
    await page.getByText('Explore EIP-712 signature tampering', { exact: true }).click();
    await page.getByRole('button', { name: 'Load signed receipt' }).click();
    await expect(page.getByText('Signature valid', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Modify receipt' }).click();
    await expect(page.getByText('Signature invalid', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Restore original' }).click();
    await expect(page.getByText('Signature valid', { exact: true })).toBeVisible();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: 'Audit control', exact: true }).click();
    await page.screenshot({ path: path.join(output, 'mobile-audit.png'), fullPage: true });
    if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw new Error('Mobile audit has horizontal overflow.');
    await page.getByRole('button', { name: 'DecisionTrail home' }).click();
    await page.screenshot({ path: path.join(output, 'landing-mobile.png'), fullPage: true });
    if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw new Error('Mobile landing has horizontal overflow.');
    await page.setViewportSize({ width: 1024, height: 768 });
    await page.screenshot({ path: path.join(output, 'landing-tablet.png') });
    if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw new Error('Tablet landing has horizontal overflow.');
    if (errors.length) throw new Error('Browser errors: ' + errors.join('; '));
    console.log('PASS: browser journey, malformed/tampered import, persistence, mined revert, resolution, checkpoint, reseal, history, tamper restoration, 390/1024/1440 layouts.');
  } catch (e) {
    await page.screenshot({ path: path.join(output, 'failure.png'), fullPage: true }).catch(() => {});
    fs.writeFileSync(path.join(output, 'failure.txt'), await page.locator('body').innerText().catch(() => 'Unavailable'));
    throw e;
  } finally {
    fs.writeFileSync(path.join(output, 'browser-errors.json'), JSON.stringify(errors, null, 2));
    await browser.close();
  }
})().catch(e => { console.error(e); process.exit(1); });


